
## Shortcuts
bindsym $mod+Return exec $tile
bindsym $mod+Shift+Return exec $term
#bindsym $mod+Ctrl+Return exec $shaell
bindsym $mod+Ctrl+Return exec $haskell_shell
bindsym Alt+Print exec $screenshot
bindsym Print exec $screenclip
bindsym $mod+d exec $menu
bindsym $mod+g exec $pacinstall
bindsym $mod+Shift+g exec $pacrm
bindsym --locked $mod+Alt+Return exec systemctl poweroff
bindsym --locked $mod+Alt+Shift+Return exec reboot
bindsym $mod+l exec $lock

bindsym $mod+Shift+q kill
bindsym $mod+Shift+t set $arg kill; $tile
bindsym $mod+Shift+c reload
bindsym $mod+h splith
bindsym $mod+v splitv
## Cycle through workspaces
bindsym $mod+tab workspace next_on_output 
bindsym $mod+Shift+tab workspace prev_on_output
bindsym $mod+grave workspace back_and_forth

## Move your focus around
bindsym $mod+Left focus left
bindsym $mod+Down focus down
bindsym $mod+Up focus up
bindsym $mod+Right focus right

## move the focused window with the same, but add Shift
bindsym $mod+Shift+Left move left
bindsym $mod+Shift+Right move right
bindsym $mod+Shift+Down move down
bindsym $mod+Shift+Up move up

## switch to workspace
bindsym $mod+1   workspace 1
bindsym $mod+2   workspace 2
bindsym $mod+3   workspace 3
bindsym $mod+4   workspace 4
bindsym $mod+5   workspace 5
bindsym $mod+6   workspace 6
bindsym $mod+7   workspace 7
bindsym $mod+8   workspace 8
bindsym $mod+9   workspace 9
bindsym $mod+0   workspace 10

## move focused container to workspace
bindsym $mod+Shift+1    move container to workspace 1
bindsym $mod+Shift+2    move container to workspace 2
bindsym $mod+Shift+3    move container to workspace 3
bindsym $mod+Shift+4    move container to workspace 4
bindsym $mod+Shift+5    move container to workspace 5
bindsym $mod+Shift+6    move container to workspace 6
bindsym $mod+Shift+7    move container to workspace 7
bindsym $mod+Shift+8    move container to workspace 8
bindsym $mod+Shift+9    move container to workspace 9
bindsym $mod+Shift+0    move container to workspace 10
#(swaymsg -t get_workspaces | jq '.. | select(.type?) | select(.focused) | .name')

#workspace back_and_forth;

## Layout stuff:

# Switch the current container between different layout styles
bindsym $mod+s layout stacking
bindsym $mod+w layout tabbed
bindsym $mod+e layout toggle split

# Make the current focus fullscreen
bindsym $mod+f fullscreen

# Toggle the current focus between tiling and floating mode
bindsym $mod+Shift+space floating toggle
# Swap focus between the tiling area and the floating area
bindsym $mod+space focus mode_toggle

# move focus to the parent container
bindsym $mod+a focus parent

# Move the currently focused window to the scratchpad
bindsym $mod+Shift+minus move scratchpad
# Show the next scratchpad window or hide the focused scratchpad window.
# If there are multiple scratchpad windows, this command cycles through them.
bindsym $mod+plus scratchpad show
